name: Run Unit Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test gateway-service
        run: make -C ./gateway-service remote_test

      - name: Test terminal-service
        run: make -C ./terminal-service remote_test

      - name: Test chatbot-service
        run: make -C ./chatbot-service remote_test
